# Generated by Django 6.0.5 on 2026-07-18 17:07

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': [('access_planning', 'Peut accéder au planning musiciens'), ('access_member_area', 'Peut accéder à l’espace adhérents')], 'verbose_name': 'utilisateur', 'verbose_name_plural': 'utilisateurs'},
        ),
        migrations.AddField(
            model_name='user',
            name='email_verified',
            field=models.BooleanField(default=False, verbose_name='E-mail vérifié'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_association_member',
            field=models.BooleanField(db_index=True, default=False, help_text='Accès espace adhérents.', verbose_name='Membre de l’association'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_musician',
            field=models.BooleanField(db_index=True, default=False, help_text='Accès planning et outils musiciens.', verbose_name='Musicien de l’orchestre'),
        ),
        migrations.AddField(
            model_name='user',
            name='membership_expires_at',
            field=models.DateField(blank=True, null=True, verbose_name='Fin d’adhésion'),
        ),
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, db_index=True, help_text='Format international recommandé (ex. +33612345678).', max_length=20, verbose_name='Téléphone'),
        ),
        migrations.AddField(
            model_name='user',
            name='phone_verified',
            field=models.BooleanField(default=False, verbose_name='Téléphone vérifié'),
        ),
        migrations.AddField(
            model_name='user',
            name='preferred_2fa_channel',
            field=models.CharField(choices=[('app', 'Application d’authentification'), ('sms', 'SMS'), ('email', 'E-mail')], default='email', max_length=10, verbose_name='Canal 2FA préféré'),
        ),
        migrations.AddField(
            model_name='user',
            name='totp_enabled',
            field=models.BooleanField(default=False, verbose_name='2FA application activée'),
        ),
        migrations.AddField(
            model_name='user',
            name='totp_secret',
            field=models.CharField(blank=True, help_text='Secret base32 pour l’application d’authentification.', max_length=64, verbose_name='Secret TOTP'),
        ),
        migrations.AddField(
            model_name='user',
            name='two_factor_enabled',
            field=models.BooleanField(default=False, help_text='Après le mot de passe, exige un second facteur (app, SMS ou e-mail).', verbose_name='Double authentification obligatoire'),
        ),
        migrations.CreateModel(
            name='AuthChallenge',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('purpose', models.CharField(choices=[('login', 'Connexion'), ('2fa', 'Double authentification'), ('verify_email', 'Vérification e-mail'), ('verify_phone', 'Vérification téléphone')], max_length=20)),
                ('channel', models.CharField(choices=[('email', 'E-mail'), ('sms', 'SMS'), ('app', 'Application')], max_length=10)),
                ('code_hash', models.CharField(max_length=128)),
                ('destination', models.CharField(blank=True, help_text='E-mail ou numéro ciblé (masqué côté UI).', max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('consumed_at', models.DateTimeField(blank=True, null=True)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('max_attempts', models.PositiveSmallIntegerField(default=5)),
                ('session_key', models.CharField(blank=True, db_index=True, max_length=40)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auth_challenges', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'défi d’authentification',
                'verbose_name_plural': 'défis d’authentification',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'purpose', 'consumed_at'], name='users_authc_user_id_85adee_idx'), models.Index(fields=['expires_at'], name='users_authc_expires_5d150f_idx')],
            },
        ),
    ]
