# Generated by Django 6.0.5 on 2026-07-19 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auth_roles_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='chat_auto_subscribe',
            field=models.BooleanField(default=True, help_text='À la création d’un événement, s’abonner automatiquement aux alertes SMS (digest) du salon associé.', verbose_name='Abonnement auto aux salons chat'),
        ),
    ]
