# Generated by Django 6.0.5 on 2026-07-19 18:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_chat_multisalon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='chat_auto_subscribe',
            field=models.BooleanField(default=True, help_text='À la création d’un événement, s’abonner automatiquement aux alertes (push ou e-mail) du salon associé.', verbose_name='Abonnement auto aux salons chat'),
        ),
        migrations.CreateModel(
            name='PushSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endpoint', models.URLField(max_length=500, unique=True, verbose_name='Endpoint')),
                ('p256dh', models.CharField(max_length=200, verbose_name='Clé p256dh')),
                ('auth', models.CharField(max_length=100, verbose_name='Clé auth')),
                ('user_agent', models.CharField(blank=True, max_length=300, verbose_name='User-Agent')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Mis à jour le')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='push_subscriptions', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'abonnement push',
                'verbose_name_plural': 'abonnements push',
                'ordering': ['-updated_at'],
            },
        ),
    ]
