# Generated by Django 6.0.5 on 2026-07-21 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_webpush_alerts'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='notify_contact_messages',
            field=models.BooleanField(default=True, help_text='Recevoir une notification (push ou e-mail) lorsqu’un message de contact ou une demande de prestation arrive.', verbose_name='Alertes messages de contact'),
        ),
        migrations.AlterField(
            model_name='authchallenge',
            name='channel',
            field=models.CharField(choices=[('email', 'E-mail'), ('sms', 'Notification'), ('app', 'Application')], max_length=10),
        ),
        migrations.AlterField(
            model_name='user',
            name='preferred_2fa_channel',
            field=models.CharField(choices=[('app', 'Application d’authentification'), ('sms', 'Notification'), ('email', 'E-mail')], default='email', max_length=10, verbose_name='Canal 2FA préféré'),
        ),
        migrations.AlterField(
            model_name='user',
            name='two_factor_enabled',
            field=models.BooleanField(default=False, help_text='Après le mot de passe, exige un second facteur (app, notification ou e-mail).', verbose_name='Double authentification obligatoire'),
        ),
    ]
