# Generated by Django 6.0.5 on 2026-07-22 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_product_tours'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='dismissed_page_leads',
            field=models.JSONField(blank=True, default=list, help_text='Clés des textes d’aide masqués en haut de page.', verbose_name='Aides de page masquées'),
        ),
    ]
