# Generated by Django 6.0.5 on 2026-07-23 16:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_dismissed_page_leads'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titre')),
                ('body', models.TextField(verbose_name='Message')),
                ('url', models.CharField(blank=True, help_text='Chemin relatif ou URL absolue (ex. /planning/).', max_length=500, verbose_name='Lien')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Créée le')),
                ('read_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Lue le')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='Destinataire')),
            ],
            options={
                'verbose_name': 'notification',
                'verbose_name_plural': 'notifications',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'read_at', '-created_at'], name='users_usern_user_id_907cbd_idx')],
            },
        ),
    ]
