# Generated by Django 6.0.5 on 2026-07-23 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_user_notifications'),
    ]

    operations = [
        migrations.AddField(
            model_name='usernotification',
            name='related_id',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='ID objet lié'),
        ),
        migrations.AddField(
            model_name='usernotification',
            name='related_type',
            field=models.CharField(blank=True, choices=[('event', 'Événement'), ('participation', 'Participation'), ('proposal', 'Sondage')], help_text='Pour marquer « répondue » quand le musicien agit.', max_length=20, verbose_name='Objet lié'),
        ),
        migrations.AddField(
            model_name='usernotification',
            name='requires_response',
            field=models.BooleanField(db_index=True, default=False, help_text='Invitation, sondage, relance… — distinct de la lecture.', verbose_name='Attend une réponse'),
        ),
        migrations.AddField(
            model_name='usernotification',
            name='responded_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Répondue le'),
        ),
        migrations.AddIndex(
            model_name='usernotification',
            index=models.Index(fields=['requires_response', 'responded_at', '-created_at'], name='users_usern_require_281349_idx'),
        ),
        migrations.AddIndex(
            model_name='usernotification',
            index=models.Index(fields=['related_type', 'related_id', 'user'], name='users_usern_related_fe2723_idx'),
        ),
    ]
