# Generated by Django 6.0.5 on 2026-09-08 18:11

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_resync_tours_admin_hub'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='notify_digest_hour',
            field=models.PositiveSmallIntegerField(default=18, help_text='Heure locale (0–23) pour les récaps (pas le temps réel).', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(23)], verbose_name='Heure du récap'),
        ),
        migrations.AddField(
            model_name='user',
            name='notify_digest_last_sent_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Dernier récap (défaut)'),
        ),
        migrations.AddField(
            model_name='user',
            name='notify_digest_weekday',
            field=models.PositiveSmallIntegerField(default=0, help_text='0 = lundi … 6 = dimanche. Utilisé si fréquence hebdomadaire.', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(6)], verbose_name='Jour du récap hebdo'),
        ),
        migrations.AddField(
            model_name='user',
            name='notify_frequency',
            field=models.CharField(choices=[('realtime', 'Temps réel'), ('daily', 'Une fois par jour'), ('every_2_days', 'Tous les deux jours'), ('every_3_days', 'Tous les trois jours'), ('weekly', 'Une fois par semaine')], default='realtime', help_text='Choix par défaut pour les alertes push / e-mail. L’historique in-app reste à jour dans tous les cas.', max_length=20, verbose_name='Fréquence des notifications'),
        ),
        migrations.CreateModel(
            name='NotificationTypePref',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notify_type', models.CharField(db_index=True, max_length=20, verbose_name='Type')),
                ('frequency', models.CharField(choices=[('realtime', 'Temps réel'), ('daily', 'Une fois par jour')], max_length=20, verbose_name='Fréquence')),
                ('digest_hour', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(23)], verbose_name='Heure du récap')),
                ('last_sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Dernier récap')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notify_type_prefs', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'préférence de notification (type)',
                'verbose_name_plural': 'préférences de notification (types)',
                'constraints': [models.UniqueConstraint(fields=('user', 'notify_type'), name='uniq_user_notify_type_pref')],
            },
        ),
    ]
