# Generated by Django 6.0.5 on 2026-05-28 13:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EventType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': "Type d'événement",
            },
        ),
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('adresse', models.CharField(blank=True, max_length=300)),
                ('ville', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Lieu',
                'ordering': ['ville', 'nom'],
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=300)),
                ('date_debut', models.DateTimeField()),
                ('date_fin', models.DateTimeField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('public', models.BooleanField(default=True)),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='events.eventtype')),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='events.venue')),
            ],
            options={
                'verbose_name': 'Événement',
                'ordering': ['date_debut'],
            },
        ),
    ]
