# Generated by Django 6.0.5 on 2026-06-03 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='statut',
            field=models.CharField(choices=[('confirme', 'Confirmé'), ('tentative', 'Date à confirmer'), ('annule', 'Annulé')], default='confirme', max_length=20),
        ),
        migrations.AddField(
            model_name='event',
            name='url_billets',
            field=models.URLField(blank=True, help_text='Lien billetterie si applicable'),
        ),
    ]
