# Generated by Django 6.0.5 on 2026-07-19 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_venue_latitude_venue_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='E-mail'),
        ),
        migrations.AddField(
            model_name='event',
            name='contact_nom',
            field=models.CharField(blank=True, help_text='Personne à contacter sur place (hors répétitions)', max_length=120, verbose_name='Contact'),
        ),
        migrations.AddField(
            model_name='event',
            name='contact_telephone',
            field=models.CharField(blank=True, max_length=40, verbose_name='Téléphone'),
        ),
    ]
