# Generated by Django 6.0.5 on 2026-07-19 17:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_event_public_parent_organisme'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='proposed_by',
            field=models.ForeignKey(blank=True, help_text='Musicien ou adhérent ayant proposé cet événement.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events_proposed', to=settings.AUTH_USER_MODEL, verbose_name='Proposé par'),
        ),
    ]
