# Generated by Django 6.0.5 on 2026-07-21 16:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_event_slug'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['public', 'date_debut'], name='event_public_date_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['date_debut'], name='event_date_debut_idx'),
        ),
    ]
