# Generated by Django 6.0.5 on 2026-07-22 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_security_perf_indexes'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='photos_request_sent_at',
            field=models.DateTimeField(blank=True, help_text='Horodatage de la notification J+7 demandant photos/vidéos aux membres.', null=True, verbose_name='Demande de photos envoyée'),
        ),
    ]
