# Generated by Django 6.0.5 on 2026-07-27 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0012_eventtype_is_rehearsal"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="shares_bluesky",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Clics sur le bouton de partage Bluesky (site).",
                verbose_name="Partages Bluesky",
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="shares_facebook",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Clics sur le bouton de partage Facebook (site).",
                verbose_name="Partages Facebook",
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="shares_instagram",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Clics sur le bouton de partage Instagram (site).",
                verbose_name="Partages Instagram",
            ),
        ),
    ]
