# Generated by Django 6.0.5 on 2026-08-24 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0013_event_share_counts'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisme',
            name='url_site',
            field=models.URLField(blank=True, help_text='Page web de l’organisme (lien sur le nom en affichage public).', verbose_name='Site web'),
        ),
    ]
