# Generated by Django 6.0.5 on 2026-09-13 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0014_organisme_url_site'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='public',
            field=models.BooleanField(default=False, help_text='Coché = l’événement apparaît sur l’accueil et /concerts/. Activé automatiquement à la validation (hors répétitions) ; dépublication via le CMS concerts.', verbose_name='Visible sur le site public'),
        ),
    ]
