# Generated by Django 6.0.5 on 2026-07-20 17:50

import django.db.models.deletion
import repertoire.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0006_event_proposed_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Piece',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titre')),
                ('slug', models.SlugField(max_length=220, unique=True, verbose_name='Slug')),
                ('is_published', models.BooleanField(default=False, help_text='Visible par les musiciens une fois publié.', verbose_name='Publié')),
                ('remarks', models.TextField(blank=True, help_text='Intro, structure, comment commencer…', verbose_name='Remarques')),
                ('chorus_order', models.TextField(blank=True, help_text='Dernière décision d’ordre des solos.', verbose_name='Ordre des chorus')),
                ('chorus_order_updated_at', models.DateTimeField(blank=True, null=True, verbose_name='Chorus mis à jour le')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
            ],
            options={
                'verbose_name': 'morceau',
                'verbose_name_plural': 'morceaux',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Setlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titre')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('is_active', models.BooleanField(default=True, help_text='Si liée à un événement, seule la setlist active est affichée.', verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créée le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifiée le')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_setlists', to=settings.AUTH_USER_MODEL, verbose_name='Créée par')),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='setlists', to='events.event', verbose_name='Événement')),
            ],
            options={
                'verbose_name': 'setlist',
                'verbose_name_plural': 'setlists',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Part',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poste', models.CharField(choices=[('alto_1', '1er alto'), ('alto_2', '2e alto'), ('tenor_1', '1er ténor'), ('tenor_2', '2e ténor'), ('baryton', 'Sax baryton'), ('trompette_1', '1er trompette'), ('trompette_2', '2e trompette'), ('trompette_3', '3e trompette'), ('trompette_4', '4e trompette'), ('trombone_1', '1er trombone'), ('trombone_2', '2e trombone'), ('trombone_3', '3e trombone'), ('trombone_4', '4e trombone (basse)'), ('piano', 'Piano'), ('guitare', 'Guitare'), ('basse', 'Basse'), ('batterie', 'Batterie'), ('clarinette', 'Clarinette'), ('chant', 'Chant'), ('percussion', 'Percussions'), ('conducteur', 'Conducteur'), ('autre', 'Autre')], db_index=True, max_length=30, verbose_name='Poste')),
                ('file', models.FileField(upload_to=repertoire.models.part_upload_to, verbose_name='Fichier PDF')),
                ('source_name', models.CharField(blank=True, max_length=255, verbose_name='Nom source')),
                ('sort_order', models.PositiveSmallIntegerField(default=0, verbose_name='Ordre')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('piece', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parts', to='repertoire.piece', verbose_name='Morceau')),
            ],
            options={
                'verbose_name': 'partition',
                'verbose_name_plural': 'partitions',
                'ordering': ['sort_order', 'poste'],
                'constraints': [models.UniqueConstraint(fields=('piece', 'poste'), name='unique_part_per_piece_poste')],
            },
        ),
        migrations.CreateModel(
            name='SetlistItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveSmallIntegerField(default=0, verbose_name='Position')),
                ('note', models.CharField(blank=True, max_length=200, verbose_name='Note')),
                ('piece', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='setlist_items', to='repertoire.piece', verbose_name='Morceau')),
                ('setlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='repertoire.setlist', verbose_name='Setlist')),
            ],
            options={
                'verbose_name': 'élément de setlist',
                'verbose_name_plural': 'éléments de setlist',
                'ordering': ['position', 'id'],
                'constraints': [models.UniqueConstraint(fields=('setlist', 'piece'), name='unique_piece_per_setlist')],
            },
        ),
    ]
