# Generated by Django 6.0.5 on 2026-07-20 18:00

import repertoire.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repertoire', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='piece',
            name='audio_recording',
            field=models.FileField(blank=True, help_text='Version propre du morceau (mp3, m4a, wav, ogg…).', upload_to=repertoire.models.piece_audio_upload_to, verbose_name='Enregistrement audio'),
        ),
        migrations.AddField(
            model_name='piece',
            name='youtube_url_1',
            field=models.URLField(blank=True, help_text='Vidéo de référence (optionnel).', max_length=500, verbose_name='Lien YouTube 1'),
        ),
        migrations.AddField(
            model_name='piece',
            name='youtube_url_2',
            field=models.URLField(blank=True, max_length=500, verbose_name='Lien YouTube 2'),
        ),
        migrations.AddField(
            model_name='piece',
            name='youtube_url_3',
            field=models.URLField(blank=True, max_length=500, verbose_name='Lien YouTube 3'),
        ),
    ]
