# Generated by Django 6.0.5 on 2026-05-28 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(help_text='ex: boutique-goodies, adhesion-helloasso', unique=True)),
                ('label', models.CharField(max_length=200)),
                ('url', models.URLField()),
                ('actif', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Lien externe',
            },
        ),
        migrations.CreateModel(
            name='MediaItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('photo', 'Photo'), ('video', 'Vidéo')], max_length=10)),
                ('titre', models.CharField(blank=True, max_length=200)),
                ('fichier', models.ImageField(blank=True, null=True, upload_to='medias/')),
                ('url_externe', models.URLField(blank=True, help_text='URL YouTube/Vimeo si vidéo')),
                ('ordre', models.PositiveIntegerField(default=0)),
                ('publie', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Média',
                'ordering': ['ordre', '-id'],
            },
        ),
    ]
