# Generated by Django 6.0.5 on 2026-06-03 09:34

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediaitem',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='mediaitem',
            name='fichier_compresse',
            field=models.FileField(blank=True, null=True, upload_to='medias/compresses/'),
        ),
        migrations.AddField(
            model_name='mediaitem',
            name='note_admin',
            field=models.TextField(blank=True, verbose_name='Note admin'),
        ),
        migrations.AddField(
            model_name='mediaitem',
            name='object_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mediaitem',
            name='soumis_le',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mediaitem',
            name='soumis_par_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='mediaitem',
            name='soumis_par_nom',
            field=models.CharField(blank=True, max_length=200, verbose_name='Soumis par'),
        ),
        migrations.AddField(
            model_name='mediaitem',
            name='statut',
            field=models.CharField(choices=[('en_attente', 'En attente de validation'), ('en_cours', 'Compression en cours'), ('publie', 'Publié'), ('refuse', 'Refusé')], default='en_attente', max_length=20),
        ),
        migrations.AlterField(
            model_name='mediaitem',
            name='fichier',
            field=models.FileField(blank=True, null=True, upload_to='medias/originaux/'),
        ),
        migrations.AlterField(
            model_name='mediaitem',
            name='publie',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='mediaitem',
            name='type',
            field=models.CharField(choices=[('photo', 'Photo'), ('video', 'Vidéo'), ('audio', 'Audio'), ('pdf', 'PDF')], max_length=10),
        ),
        migrations.AlterField(
            model_name='mediaitem',
            name='url_externe',
            field=models.URLField(blank=True, help_text='URL YouTube/Vimeo si vidéo externe'),
        ),
    ]
