# Generated by Django 6.0.5 on 2026-06-03 10:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_mediaitem_content_type_mediaitem_fichier_compresse_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EvenementMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200, unique=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('ordre', models.PositiveIntegerField(default=0)),
                ('evenement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medias', to='core.evenementmedia', verbose_name='Événement')),
            ],
            options={
                'verbose_name': 'Événement média',
                'verbose_name_plural': 'Événements médias',
                'ordering': ['-date', 'ordre', 'nom'],
            },
        ),
    ]
