# Generated by Django 6.0.5 on 2026-06-03 11:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_evenementmedia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evenementmedia',
            name='evenement',
        ),
        migrations.AddField(
            model_name='mediaitem',
            name='evenement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='core.evenementmedia', verbose_name='Événement'),
        ),
    ]
