# Generated by Django 6.0.5 on 2026-06-03 11:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_evenementmedia_evenement_mediaitem_evenement'),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(max_length=40)),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('media', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='core.mediaitem')),
            ],
            options={
                'verbose_name': 'Vote',
                'unique_together': {('media', 'session_key')},
            },
        ),
    ]
