# Generated by Django 6.0.5 on 2026-06-03 16:48

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_mediavote'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=120)),
                ('telephone', models.CharField(blank=True, max_length=40)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
                ('statut', models.CharField(choices=[('new', 'Nouveau'), ('read', 'Lu'), ('processed', 'Traité'), ('archived', 'Archivé')], db_index=True, default='new', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Message de contact',
                'verbose_name_plural': 'Messages de contact',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='evenementmedia',
            options={'ordering': ['-date', 'nom'], 'verbose_name': 'Événement média', 'verbose_name_plural': 'Événements média'},
        ),
        migrations.AlterModelOptions(
            name='externallink',
            options={'verbose_name': 'Lien externe', 'verbose_name_plural': 'Liens externes'},
        ),
        migrations.AlterModelOptions(
            name='mediaitem',
            options={'ordering': ['ordre', 'id'], 'verbose_name': 'Média', 'verbose_name_plural': 'Médias'},
        ),
        migrations.AlterModelOptions(
            name='mediavote',
            options={'verbose_name': 'Vote média', 'verbose_name_plural': 'Votes médias'},
        ),
        migrations.RenameField(
            model_name='mediavote',
            old_name='cree_le',
            new_name='created_at',
        ),
        migrations.AlterUniqueTogether(
            name='mediavote',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='evenementmedia',
            name='ordre',
        ),
        migrations.RenameField(
            model_name='externallink',
            old_name='label',
            new_name='titre',
        ),
        migrations.RemoveField(
            model_name='mediaitem',
            name='fichier_compresse',
        ),
        migrations.AddField(
            model_name='evenementmedia',
            name='lieu',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='externallink',
            name='titre',
            field=models.CharField(max_length=120),
        ),
        migrations.AddField(
            model_name='mediaitem',
            name='miniature',
            field=models.ImageField(blank=True, null=True, upload_to='medias/thumbs/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='evenementmedia',
            name='nom',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='externallink',
            name='slug',
            field=models.SlugField(unique=True),
        ),
        migrations.AlterField(
            model_name='mediaitem',
            name='evenement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='core.evenementmedia'),
        ),
        migrations.AlterField(
            model_name='mediaitem',
            name='fichier',
            field=models.FileField(blank=True, null=True, upload_to='medias/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='mediaitem',
            name='note_admin',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='mediaitem',
            name='soumis_le',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='mediaitem',
            name='soumis_par_nom',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AlterField(
            model_name='mediaitem',
            name='statut',
            field=models.CharField(choices=[('en_attente', 'En attente'), ('publie', 'Publié'), ('refuse', 'Refusé')], default='en_attente', max_length=20),
        ),
        migrations.AlterField(
            model_name='mediaitem',
            name='titre',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='mediaitem',
            name='url_externe',
            field=models.URLField(blank=True),
        ),
        migrations.AddConstraint(
            model_name='mediavote',
            constraint=models.UniqueConstraint(fields=('media', 'session_key'), name='unique_vote_par_session'),
        ),
    ]
