# Generated by Django 6.0.5 on 2026-07-25 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_contactmessage_alter_evenementmedia_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediaitem',
            name='statut',
            field=models.CharField(choices=[('en_attente', 'En attente'), ('en_cours', 'Compression en cours'), ('publie', 'Publié'), ('refuse', 'Refusé')], default='en_attente', max_length=20),
        ),
    ]
