# Generated by Django 6.0.5 on 2026-07-21 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_contactmessage_alter_evenementmedia_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmessage',
            name='acces_logistique',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='budget',
            field=models.CharField(blank=True, choices=[('indet', 'À définir'), ('lt500', 'Moins de 500 €'), ('500_1000', '500 – 1 000 €'), ('gt1000', 'Plus de 1 000 €')], max_length=20),
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='date_alternative',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='date_flexible',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='date_souhaitee',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='duree_jeu',
            field=models.CharField(blank=True, choices=[('45', 'Environ 45 min'), ('60', 'Environ 1 h'), ('90', 'Environ 1 h 30'), ('120', '2 h ou plus'), ('indet', 'À définir')], max_length=10),
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='heure_debut',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='heure_fin',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='jauge',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='kind',
            field=models.CharField(choices=[('contact', 'Contact'), ('prestation', 'Demande de prestation')], db_index=True, default='contact', max_length=20),
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='lieu_adresse',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='lieu_nom',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='lieu_type',
            field=models.CharField(blank=True, choices=[('interieur', 'Intérieur'), ('exterieur', 'Extérieur'), ('mixte', 'Mixte')], max_length=20),
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='organisation',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='profil',
            field=models.CharField(blank=True, choices=[('particulier', 'Particulier'), ('association', 'Association'), ('entreprise', 'Entreprise'), ('collectivite', 'Collectivité'), ('agence', 'Agence'), ('autre', 'Autre')], max_length=20),
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='role_ambiance',
            field=models.CharField(blank=True, choices=[('concert', 'Concert assis'), ('cocktail', 'Cocktail / fond sonore'), ('danse', 'Danse'), ('ceremonie', 'Cérémonie'), ('autre', 'Autre')], max_length=20),
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='scene_details',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='sono',
            field=models.CharField(blank=True, choices=[('pa_complet', 'Le lieu fournit un PA complet'), ('pa_basique', 'Le lieu fournit un PA basique'), ('a_charge', 'Sono à la charge de l’orchestre'), ('indet', 'Je ne sais pas')], max_length=20),
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='source',
            field=models.CharField(blank=True, choices=[('site', 'Site web'), ('social', 'Réseaux sociaux'), ('bouche', 'Bouche à oreille'), ('lieu', 'Recommandation d’un lieu'), ('concert', 'Après un concert'), ('autre', 'Autre')], max_length=20),
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='type_evenement',
            field=models.CharField(blank=True, choices=[('concert', 'Concert public'), ('festival', 'Festival'), ('mariage', 'Mariage / réception'), ('entreprise', 'Entreprise / gala'), ('bal', 'Bal / danse'), ('prive', 'Événement privé'), ('autre', 'Autre')], max_length=20),
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='ville',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='message',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='mediaitem',
            name='statut',
            field=models.CharField(choices=[('en_attente', 'En attente'), ('en_cours', 'Compression en cours'), ('publie', 'Publié'), ('refuse', 'Refusé')], default='en_attente', max_length=20),
        ),
    ]
