# Generated by Django 6.0.5 on 2026-07-21 16:23

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('core', '0009_mediaitem_fichier_edite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediaitem',
            name='fichier',
            field=models.FileField(blank=True, null=True, upload_to=core.models.media_upload_to),
        ),
        migrations.AddIndex(
            model_name='mediaitem',
            index=models.Index(fields=['type', 'publie'], name='core_media_type_publie_idx'),
        ),
        migrations.AddIndex(
            model_name='mediaitem',
            index=models.Index(fields=['statut', 'soumis_le'], name='core_media_statut_soumis_idx'),
        ),
    ]
