# Generated by Django 6.0.5 on 2026-09-09 12:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_seo_accueil_meta_prestations_cta'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffMailing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=200)),
                ('body_template', models.TextField(help_text='Corps avec placeholder {{prenom}} pour les musiciens.')),
                ('recipients', models.JSONField(default=list, help_text='Liste de {email, prenom, user_id, status, error?}.')),
                ('sent_count', models.PositiveIntegerField(default=0)),
                ('failed_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_mailings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Envoi e-mail staff',
                'verbose_name_plural': 'Envois e-mail staff',
                'ordering': ['-created_at'],
            },
        ),
    ]
