# Generated by Django 6.0.5 on 2026-07-18 18:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PageFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('BUG', 'Bug'), ('COMFORT', 'Confort de la vue'), ('MISSING_FEATURE', 'Fonctionnalité manquante')], max_length=20, verbose_name='Type de retour')),
                ('importance', models.PositiveSmallIntegerField(blank=True, choices=[(1, '1 — Pas important'), (2, '2'), (3, '3'), (4, '4'), (5, '5 — Très important')], help_text='Importance affichée (1 à 5), arrondie à partir du score bayésien.', null=True, verbose_name='Importance')),
                ('importance_score', models.DecimalField(blank=True, decimal_places=4, help_text='Score bayésien (note + effectif des votes) pour le tri.', max_digits=6, null=True, verbose_name="Score d'importance")),
                ('admin_priority', models.PositiveSmallIntegerField(blank=True, choices=[(1, '1 — Faible'), (2, '2'), (3, '3'), (4, '4'), (5, '5 — Urgent')], help_text="Urgence définie par l'administrateur (1 à 5).", null=True, verbose_name='Priorité admin')),
                ('message', models.TextField(verbose_name='Message')),
                ('page_url', models.CharField(max_length=500, verbose_name='Page concernée')),
                ('page_title', models.CharField(blank=True, max_length=200, verbose_name='Titre de la page')),
                ('page_context', models.TextField(blank=True, verbose_name='Contexte page (JSON)')),
                ('status', models.CharField(choices=[('NEW', 'Nouveau'), ('READ', 'Lu')], default='NEW', max_length=10, verbose_name='Statut')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='Lu le')),
                ('author_notified_at', models.DateTimeField(blank=True, null=True, verbose_name='Auteur informé le')),
                ('author_response_seen_at', models.DateTimeField(blank=True, null=True, verbose_name="Réponse lue par l'auteur le")),
                ('treated_at', models.DateTimeField(blank=True, null=True, verbose_name='Traité le')),
                ('in_progress_at', models.DateTimeField(blank=True, null=True, verbose_name='En cours le')),
                ('snoozed_until', models.DateTimeField(blank=True, null=True, verbose_name='Reporté jusqu’au')),
                ('snoozed_at', models.DateTimeField(blank=True, null=True, verbose_name='Reporté le')),
                ('vote_formulation', models.TextField(blank=True, help_text="Texte reformulé par l'administrateur soumis au vote.", verbose_name='Formulation au vote')),
                ('vote_roles', models.JSONField(blank=True, default=list, help_text='Liste de rôles JOY (musician, association_member, staff).', verbose_name='Rôles éligibles au vote')),
                ('vote_opened_at', models.DateTimeField(blank=True, null=True, verbose_name='Vote ouvert le')),
                ('vote_closed_at', models.DateTimeField(blank=True, null=True, verbose_name='Vote clos le')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='page_feedbacks', to=settings.AUTH_USER_MODEL, verbose_name='Auteur')),
                ('author_notified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='page_feedbacks_author_notified', to=settings.AUTH_USER_MODEL, verbose_name='Informé par')),
                ('in_progress_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='page_feedbacks_marked_in_progress', to=settings.AUTH_USER_MODEL, verbose_name='En cours par')),
                ('read_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='page_feedbacks_marked_read', to=settings.AUTH_USER_MODEL, verbose_name='Lu par')),
                ('snoozed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='page_feedbacks_snoozed', to=settings.AUTH_USER_MODEL, verbose_name='Reporté par')),
                ('treated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='page_feedbacks_marked_treated', to=settings.AUTH_USER_MODEL, verbose_name='Traité par')),
                ('vote_closed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='page_feedbacks_votes_closed', to=settings.AUTH_USER_MODEL, verbose_name='Vote clos par')),
                ('vote_opened_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='page_feedbacks_votes_opened', to=settings.AUTH_USER_MODEL, verbose_name='Vote ouvert par')),
            ],
            options={
                'verbose_name': 'Retour utilisateur',
                'verbose_name_plural': 'Retours utilisateurs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PageFeedbackRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('importance', models.PositiveSmallIntegerField(choices=[(1, '1 — Pas important'), (2, '2'), (3, '3'), (4, '4'), (5, '5 — Très important')], verbose_name='Importance')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('feedback', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='feedback.pagefeedback', verbose_name='Retour')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='page_feedback_ratings', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Soutien sur un retour',
                'verbose_name_plural': 'Soutiens sur les retours',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('feedback', 'user'), name='feedback_pagefeedbackrating_feedback_user_uniq')],
            },
        ),
        migrations.CreateModel(
            name='PageFeedbackVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice', models.CharField(choices=[('FOR', 'Pour'), ('AGAINST', 'Contre')], max_length=10, verbose_name='Choix')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date')),
                ('feedback', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='feedback.pagefeedback', verbose_name='Retour')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='page_feedback_votes', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Vote sur une proposition',
                'verbose_name_plural': 'Votes sur les propositions',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('feedback', 'user'), name='feedback_pagefeedbackvote_feedback_user_uniq')],
            },
        ),
    ]
