# Generated by Django 6.0.5 on 2026-09-08 17:54

import feedback.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagefeedback',
            name='attachment',
            field=models.FileField(blank=True, help_text='Capture d’écran ou image jointe au retour (optionnel).', null=True, upload_to=feedback.models.feedback_attachment_upload_to, verbose_name='Pièce jointe'),
        ),
    ]
