# Generated by Django 6.0.5 on 2026-09-10 11:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0002_pagefeedback_attachment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PageFeedbackMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(verbose_name='Message')),
                ('is_from_staff', models.BooleanField(default=False, verbose_name='Message staff')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date')),
                ('feedback', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='thread_messages', to='feedback.pagefeedback', verbose_name='Retour')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='page_feedback_messages', to=settings.AUTH_USER_MODEL, verbose_name='Expéditeur')),
            ],
            options={
                'verbose_name': 'Message sur un retour',
                'verbose_name_plural': 'Messages sur les retours',
                'ordering': ['created_at'],
            },
        ),
    ]
