# Generated by Django 6.0.5 on 2026-07-22 06:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UsageEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, help_text='Ex. planning.view, repertoire.pdf, chat.view', max_length=64, verbose_name='Événement')),
                ('path', models.CharField(blank=True, max_length=300, verbose_name='Chemin')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Date')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usage_events', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'événement d’usage',
                'verbose_name_plural': 'événements d’usage',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['name', 'created_at'], name='stats_usage_name_dec2e3_idx'), models.Index(fields=['user', 'created_at'], name='stats_usage_user_id_198ae3_idx')],
            },
        ),
    ]
