# Generated by Django 6.0.5 on 2026-07-22 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublicPageView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(db_index=True, max_length=300, verbose_name='Chemin')),
                ('session_key', models.CharField(blank=True, db_index=True, help_text='Identifiant de session Django (pas d’IP stockée).', max_length=40, verbose_name='Clé de session')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Date')),
            ],
            options={
                'verbose_name': 'vue page publique',
                'verbose_name_plural': 'vues pages publiques',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['created_at', 'path'], name='stats_publi_created_b2d03e_idx'), models.Index(fields=['session_key', 'created_at'], name='stats_publi_session_3a5a9a_idx')],
            },
        ),
    ]
