# Generated by Django 6.0.5 on 2026-07-19 16:45

import chat.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0004_event_contact_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(blank=True, verbose_name='Message')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Envoyé le')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Supprimé le')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chat_messages', to=settings.AUTH_USER_MODEL, verbose_name='Auteur')),
            ],
            options={
                'verbose_name': 'message',
                'verbose_name_plural': 'messages',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ChatAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=chat.models.chat_attachment_upload_to, verbose_name='Fichier')),
                ('original_name', models.CharField(max_length=255, verbose_name='Nom original')),
                ('content_type', models.CharField(blank=True, max_length=120, verbose_name='Type MIME')),
                ('size', models.PositiveBigIntegerField(default=0, verbose_name='Taille (octets)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ajouté le')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='chat.chatmessage', verbose_name='Message')),
            ],
            options={
                'verbose_name': 'pièce jointe',
                'verbose_name_plural': 'pièces jointes',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ChatRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('orchestra', 'Orchestre'), ('event', 'Événement')], db_index=True, max_length=20, verbose_name='Type')),
                ('title', models.CharField(max_length=200, verbose_name='Titre')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('event', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chat_room', to='events.event', verbose_name='Événement')),
            ],
            options={
                'verbose_name': 'salon',
                'verbose_name_plural': 'salons',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chat.chatroom', verbose_name='Salon'),
        ),
        migrations.CreateModel(
            name='ChatMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscribed', models.BooleanField(default=True, help_text='Reçoit un digest SMS des nouveaux messages.', verbose_name='Alertes SMS (digest)')),
                ('joined_at', models.DateTimeField(auto_now_add=True, verbose_name='Rejoint le')),
                ('left_at', models.DateTimeField(blank=True, null=True, verbose_name='Quitté le')),
                ('last_read_at', models.DateTimeField(blank=True, null=True, verbose_name='Dernière lecture')),
                ('last_digested_message_id', models.PositiveBigIntegerField(default=0, help_text='ID du dernier message inclus dans un digest SMS.', verbose_name='Dernier message digéré')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_memberships', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='chat.chatroom', verbose_name='Salon')),
            ],
            options={
                'verbose_name': 'appartenance salon',
                'verbose_name_plural': 'appartenances salon',
                'ordering': ['room_id', 'user_id'],
            },
        ),
        migrations.AddConstraint(
            model_name='chatroom',
            constraint=models.UniqueConstraint(condition=models.Q(('kind', 'orchestra')), fields=('kind',), name='unique_orchestra_chat_room'),
        ),
        migrations.AddConstraint(
            model_name='chatmembership',
            constraint=models.UniqueConstraint(fields=('room', 'user'), name='unique_chat_membership'),
        ),
    ]
