# Generated by Django 6.0.5 on 2026-07-19 17:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_chat_multisalon'),
        ('planning', '0007_event_propose_poll_launch'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='kind',
            field=models.CharField(choices=[('normal', 'Message'), ('poll_launch', 'Lancement de sondage'), ('system', 'Système')], db_index=True, default='normal', max_length=20, verbose_name='Type'),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='related_proposal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chat_messages', to='planning.dateproposal', verbose_name='Sondage lié'),
        ),
    ]
