# Generated by Django 6.0.5 on 2026-07-19 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_event_propose_poll_launch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmembership',
            name='last_digested_message_id',
            field=models.PositiveBigIntegerField(default=0, help_text='ID du dernier message inclus dans un digest d’alertes.', verbose_name='Dernier message digéré'),
        ),
        migrations.AlterField(
            model_name='chatmembership',
            name='subscribed',
            field=models.BooleanField(default=True, help_text='Reçoit un digest (push ou e-mail) des nouveaux messages.', verbose_name='Alertes (digest)'),
        ),
    ]
