# Generated by Django 6.0.5 on 2026-07-20 17:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_webpush_alerts'),
        ('repertoire', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroom',
            name='piece',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chat_room', to='repertoire.piece', verbose_name='Morceau'),
        ),
        migrations.AlterField(
            model_name='chatroom',
            name='kind',
            field=models.CharField(choices=[('orchestra', 'Orchestre'), ('event', 'Événement'), ('piece', 'Morceau')], db_index=True, max_length=20, verbose_name='Type'),
        ),
    ]
