# Generated by Django 6.0.5 on 2026-07-21 16:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_chatroom_piece_alter_chatroom_kind'),
        ('planning', '0010_security_perf_indexes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='chatmessage',
            index=models.Index(fields=['room', 'created_at'], name='chat_msg_room_created_idx'),
        ),
        migrations.AddIndex(
            model_name='chatmessage',
            index=models.Index(fields=['room', 'deleted_at', 'created_at'], name='chat_msg_room_del_created_idx'),
        ),
    ]
