# Generated by Django 6.0.5 on 2026-07-25 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0006_chat_message_reaction"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chatroom",
            name="kind",
            field=models.CharField(
                choices=[
                    ("orchestra", "Orchestre"),
                    ("event", "Événement"),
                    ("piece", "Morceau"),
                    ("staff", "Staff"),
                ],
                db_index=True,
                max_length=20,
                verbose_name="Type",
            ),
        ),
        migrations.AddConstraint(
            model_name="chatroom",
            constraint=models.UniqueConstraint(
                condition=models.Q(("kind", "staff")),
                fields=("kind",),
                name="unique_staff_chat_room",
            ),
        ),
    ]
