# Generated by Django 6.0.5 on 2026-09-08 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0011_chatroom_section_pupitre'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmembership',
            name='notify_digest_hour',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Heure du récap (salon)'),
        ),
        migrations.AddField(
            model_name='chatmembership',
            name='notify_digest_last_sent_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Dernier récap (salon)'),
        ),
        migrations.AddField(
            model_name='chatmembership',
            name='notify_frequency_override',
            field=models.CharField(blank=True, default='', help_text='Vide = suivre le défaut. « realtime » ou « daily » pour forcer.', max_length=20, verbose_name='Fréquence (salon)'),
        ),
        migrations.AlterField(
            model_name='chatmembership',
            name='subscribed',
            field=models.BooleanField(default=True, help_text='Reçoit les alertes (push ou e-mail) des nouveaux messages.', verbose_name='Alertes'),
        ),
    ]
