# Generated by Django 6.0.5 on 2026-09-13 09:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0014_chatroom_rehearsals_singleton'),
        ('events', '0015_chatmessage_thread_event'),
        ('planning', '0017_chatmessage_thread_event'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='thread_event',
            field=models.ForeignKey(blank=True, help_text='Dans le salon Répétitions : messages rattachés à une date.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chat_thread_messages', to='events.event', verbose_name='Fil répétition'),
        ),
        migrations.AddIndex(
            model_name='chatmessage',
            index=models.Index(fields=['room', 'thread_event', 'created_at'], name='chat_msg_thread_created_idx'),
        ),
    ]
