# Generated by Django 6.0.5 on 2026-07-22 06:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0008_security_perf_indexes'),
        ('repertoire', '0002_piece_youtube_and_audio'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RehearsalPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField(blank=True, help_text='Consignes, focus de la séance…', verbose_name='Notes générales')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Mis à jour le')),
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rehearsal_plan', to='events.event', verbose_name='Événement')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_rehearsal_plans', to=settings.AUTH_USER_MODEL, verbose_name='Mis à jour par')),
            ],
            options={
                'verbose_name': 'feuille de route',
                'verbose_name_plural': 'feuilles de route',
                'ordering': ['-event__date_debut'],
            },
        ),
        migrations.CreateModel(
            name='RehearsalItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveSmallIntegerField(default=1, verbose_name='Ordre')),
                ('note', models.CharField(blank=True, help_text='Ex. intro + chorus sax', max_length=300, verbose_name='Note')),
                ('piece', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rehearsal_items', to='repertoire.piece', verbose_name='Morceau')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='repetitions.rehearsalplan', verbose_name='Feuille de route')),
            ],
            options={
                'verbose_name': 'morceau de répétition',
                'verbose_name_plural': 'morceaux de répétition',
                'ordering': ['position', 'id'],
                'constraints': [models.UniqueConstraint(fields=('plan', 'piece'), name='unique_rehearsal_item_per_plan_piece')],
            },
        ),
    ]
