# Generated by Django 6.0.5 on 2026-05-28 14:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ParticipationStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(help_text='Clé technique stable (ex : invited, confirmed, declined)', unique=True, verbose_name='Code')),
                ('label', models.CharField(max_length=100, verbose_name='Libellé')),
                ('color_token', models.CharField(blank=True, help_text='Ex : success, warning, danger, neutral', max_length=50, verbose_name='Token couleur')),
                ('sort_order', models.PositiveSmallIntegerField(default=0, verbose_name='Ordre d’affichage')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
            ],
            options={
                'verbose_name': 'Statut de participation',
                'verbose_name_plural': 'Statuts de participation',
                'ordering': ['sort_order', 'label'],
            },
        ),
        migrations.CreateModel(
            name='EventParticipation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(blank=True, verbose_name='Commentaire')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participations', to='events.event', verbose_name='Concert')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_participations', to=settings.AUTH_USER_MODEL, verbose_name='Musicien')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='participations', to='planning.participationstatus', verbose_name='Statut')),
            ],
            options={
                'verbose_name': 'Participation concert',
                'verbose_name_plural': 'Participations concerts',
                'ordering': ['event__date_debut', 'user__last_name', 'user__first_name'],
                'constraints': [models.UniqueConstraint(fields=('event', 'user'), name='unique_event_participation_per_user')],
            },
        ),
    ]
