# Generated by Django 6.0.5 on 2026-07-18 18:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_venue_latitude_venue_longitude'),
        ('planning', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DateOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starts_at', models.DateTimeField(verbose_name='Début')),
                ('ends_at', models.DateTimeField(blank=True, null=True, verbose_name='Fin')),
                ('label', models.CharField(blank=True, max_length=120, verbose_name='Libellé')),
                ('sort_order', models.PositiveSmallIntegerField(default=0, verbose_name='Ordre')),
            ],
            options={
                'verbose_name': 'Option de date',
                'verbose_name_plural': 'Options de date',
                'ordering': ['sort_order', 'starts_at'],
            },
        ),
        migrations.CreateModel(
            name='EquipmentItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Nom')),
                ('category', models.CharField(blank=True, max_length=80, verbose_name='Catégorie')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('sort_order', models.PositiveSmallIntegerField(default=0, verbose_name='Ordre')),
            ],
            options={
                'verbose_name': 'Matériel',
                'verbose_name_plural': 'Matériels',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='OrchestraSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(unique=True, verbose_name='Code')),
                ('name', models.CharField(max_length=100, verbose_name='Nom')),
                ('sort_order', models.PositiveSmallIntegerField(default=0, verbose_name='Ordre')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
            ],
            options={
                'verbose_name': 'Pupitre',
                'verbose_name_plural': 'Pupitres',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='DateProposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titre')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('status', models.CharField(choices=[('open', 'Ouvert'), ('locked', 'Verrouillé'), ('cancelled', 'Annulé')], default='open', max_length=20, verbose_name='Statut')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='date_proposals_created', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
                ('linked_event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='from_proposals', to='events.event', verbose_name='Événement lié')),
                ('locked_option', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='planning.dateoption', verbose_name='Option retenue')),
            ],
            options={
                'verbose_name': 'Sondage de dates',
                'verbose_name_plural': 'Sondages de dates',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='dateoption',
            name='proposal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='planning.dateproposal', verbose_name='Sondage'),
        ),
        migrations.CreateModel(
            name='MusicianProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instrument', models.CharField(blank=True, help_text='Précision libre (ex. trompette 2, batterie).', max_length=100, verbose_name='Instrument')),
                ('is_substitute_pool', models.BooleanField(default=False, help_text='Peut être sollicité pour remplacer un musicien du même pupitre.', verbose_name='Pool de remplaçants')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='musician_profile', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
                ('section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='musicians', to='planning.orchestrasection', verbose_name='Pupitre')),
            ],
            options={
                'verbose_name': 'Profil musicien',
                'verbose_name_plural': 'Profils musiciens',
                'ordering': ['user__last_name', 'user__first_name'],
            },
        ),
        migrations.CreateModel(
            name='DateVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice', models.CharField(choices=[('yes', 'Oui'), ('no', 'Non'), ('maybe', 'Peut-être')], max_length=10, verbose_name='Vote')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='planning.dateoption', verbose_name='Option')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='date_votes', to=settings.AUTH_USER_MODEL, verbose_name='Musicien')),
            ],
            options={
                'verbose_name': 'Vote de date',
                'verbose_name_plural': 'Votes de date',
                'constraints': [models.UniqueConstraint(fields=('option', 'user'), name='unique_date_vote_per_option_user')],
            },
        ),
        migrations.CreateModel(
            name='EventEquipmentAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('needed', 'À prévoir'), ('ok', 'OK'), ('missing', 'Manquant')], default='needed', max_length=20, verbose_name='Statut')),
                ('notes', models.CharField(blank=True, max_length=255, verbose_name='Notes')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipment_assignments', to=settings.AUTH_USER_MODEL, verbose_name='Apporté par')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipment_assignments', to='events.event', verbose_name='Événement')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='planning.equipmentitem', verbose_name='Matériel')),
            ],
            options={
                'verbose_name': 'Matériel d’événement',
                'verbose_name_plural': 'Matériels d’événement',
                'ordering': ['item__sort_order', 'item__name'],
                'constraints': [models.UniqueConstraint(fields=('event', 'item'), name='unique_equipment_per_event_item')],
            },
        ),
        migrations.CreateModel(
            name='SubstituteRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('proposed', 'Proposé'), ('accepted', 'Accepté'), ('declined', 'Refusé'), ('cancelled', 'Annulé')], default='proposed', max_length=20, verbose_name='Statut')),
                ('note', models.CharField(blank=True, max_length=255, verbose_name='Note')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='substitute_offers', to=settings.AUTH_USER_MODEL, verbose_name='Candidat remplaçant')),
                ('participation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='substitute_requests', to='planning.eventparticipation', verbose_name='Participation d’origine')),
            ],
            options={
                'verbose_name': 'Demande de remplaçant',
                'verbose_name_plural': 'Demandes de remplaçants',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('participation', 'candidate'), name='unique_substitute_per_participation_candidate')],
            },
        ),
    ]
