# Generated by Django 6.0.5 on 2026-07-19 17:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0006_section_from_poste_titulaire'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='dateproposal',
            name='launched_at',
            field=models.DateTimeField(blank=True, help_text='Date à laquelle le staff a ouvert le sondage aux musiciens.', null=True, verbose_name='Lancé le'),
        ),
        migrations.AddField(
            model_name='dateproposal',
            name='launched_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='date_proposals_launched', to=settings.AUTH_USER_MODEL, verbose_name='Lancé par'),
        ),
        migrations.AlterField(
            model_name='dateproposal',
            name='status',
            field=models.CharField(choices=[('draft', 'Brouillon (en attente staff)'), ('open', 'Ouvert'), ('locked', 'Verrouillé'), ('cancelled', 'Annulé')], default='draft', max_length=20, verbose_name='Statut'),
        ),
    ]
