# Generated by Django 6.0.5 on 2026-07-21 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0008_eventparticipation_poste_convoque'),
    ]

    operations = [
        migrations.AddField(
            model_name='musicianprofile',
            name='poste_remplacant_2',
            field=models.CharField(blank=True, choices=[('alto_1', '1er alto'), ('alto_2', '2e alto'), ('tenor_1', '1er ténor'), ('tenor_2', '2e ténor'), ('baryton', 'Sax baryton'), ('trompette_1', '1er trompette'), ('trompette_2', '2e trompette'), ('trompette_3', '3e trompette'), ('trompette_4', '4e trompette'), ('trombone_1', '1er trombone'), ('trombone_2', '2e trombone'), ('trombone_3', '3e trombone'), ('trombone_4', '4e trombone (basse)'), ('piano', 'Piano'), ('guitare', 'Guitare'), ('basse', 'Basse'), ('batterie', 'Batterie'), ('clarinette', 'Clarinette'), ('chant', 'Chant'), ('percussion', 'Percussions')], max_length=30, verbose_name='Poste remplaçant 2'),
        ),
        migrations.AddField(
            model_name='musicianprofile',
            name='poste_remplacant_3',
            field=models.CharField(blank=True, choices=[('alto_1', '1er alto'), ('alto_2', '2e alto'), ('tenor_1', '1er ténor'), ('tenor_2', '2e ténor'), ('baryton', 'Sax baryton'), ('trompette_1', '1er trompette'), ('trompette_2', '2e trompette'), ('trompette_3', '3e trompette'), ('trompette_4', '4e trompette'), ('trombone_1', '1er trombone'), ('trombone_2', '2e trombone'), ('trombone_3', '3e trombone'), ('trombone_4', '4e trombone (basse)'), ('piano', 'Piano'), ('guitare', 'Guitare'), ('basse', 'Basse'), ('batterie', 'Batterie'), ('clarinette', 'Clarinette'), ('chant', 'Chant'), ('percussion', 'Percussions')], max_length=30, verbose_name='Poste remplaçant 3'),
        ),
        migrations.AddField(
            model_name='musicianprofile',
            name='poste_remplacant_4',
            field=models.CharField(blank=True, choices=[('alto_1', '1er alto'), ('alto_2', '2e alto'), ('tenor_1', '1er ténor'), ('tenor_2', '2e ténor'), ('baryton', 'Sax baryton'), ('trompette_1', '1er trompette'), ('trompette_2', '2e trompette'), ('trompette_3', '3e trompette'), ('trompette_4', '4e trompette'), ('trombone_1', '1er trombone'), ('trombone_2', '2e trombone'), ('trombone_3', '3e trombone'), ('trombone_4', '4e trombone (basse)'), ('piano', 'Piano'), ('guitare', 'Guitare'), ('basse', 'Basse'), ('batterie', 'Batterie'), ('clarinette', 'Clarinette'), ('chant', 'Chant'), ('percussion', 'Percussions')], max_length=30, verbose_name='Poste remplaçant 4'),
        ),
        migrations.AlterField(
            model_name='musicianprofile',
            name='poste_remplacant',
            field=models.CharField(blank=True, choices=[('alto_1', '1er alto'), ('alto_2', '2e alto'), ('tenor_1', '1er ténor'), ('tenor_2', '2e ténor'), ('baryton', 'Sax baryton'), ('trompette_1', '1er trompette'), ('trompette_2', '2e trompette'), ('trompette_3', '3e trompette'), ('trompette_4', '4e trompette'), ('trombone_1', '1er trombone'), ('trombone_2', '2e trombone'), ('trombone_3', '3e trombone'), ('trombone_4', '4e trombone (basse)'), ('piano', 'Piano'), ('guitare', 'Guitare'), ('basse', 'Basse'), ('batterie', 'Batterie'), ('clarinette', 'Clarinette'), ('chant', 'Chant'), ('percussion', 'Percussions')], help_text='1re chaise de remplacement. Laisser vide si non remplaçant.', max_length=30, verbose_name='Poste remplaçant'),
        ),
    ]
