# Generated by Django 6.0.5 on 2026-07-21 16:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_security_perf_indexes'),
        ('planning', '0009_musician_multi_postes_remplacant'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='dateproposal',
            index=models.Index(fields=['status'], name='plan_proposal_status_idx'),
        ),
        migrations.AddIndex(
            model_name='eventparticipation',
            index=models.Index(fields=['event', 'status'], name='plan_part_event_status_idx'),
        ),
        migrations.AddIndex(
            model_name='eventparticipation',
            index=models.Index(fields=['user', 'event'], name='plan_part_user_event_idx'),
        ),
    ]
