# Generated by Django 6.0.5 on 2026-07-22 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0011_musician_poste_remplacant_5'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventparticipation',
            name='maybe_last_reminded_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Dernière relance « peut-être »'),
        ),
        migrations.AddField(
            model_name='eventparticipation',
            name='maybe_remind_at',
            field=models.DateField(blank=True, help_text='Date à laquelle renvoyer la question de disponibilité.', null=True, verbose_name='Prochaine relance « peut-être »'),
        ),
        migrations.AddField(
            model_name='eventparticipation',
            name='maybe_remind_weekly',
            field=models.BooleanField(default=False, help_text='Si vrai, après chaque relance la suivante est planifiée +7 jours.', verbose_name='Relance hebdomadaire'),
        ),
    ]
