# Generated by Django 6.0.5 on 2026-07-27 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0012_eventparticipation_maybe_remind'),
    ]

    operations = [
        migrations.AddField(
            model_name='dateproposal',
            name='deadline',
            field=models.DateField(blank=True, help_text='Date avant laquelle les musiciens doivent répondre au sondage.', null=True, verbose_name='Date limite de réponse'),
        ),
    ]
