# Generated by Django 6.0.5 on 2026-07-27 15:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0012_eventtype_is_rehearsal'),
        ('planning', '0013_dateproposal_deadline'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EventRoadmap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maps_url', models.URLField(blank=True, help_text='Google Maps ou autre. Prérempli depuis les coordonnées du lieu si possible.', verbose_name='Lien carte')),
                ('venue_extra', models.CharField(blank=True, help_text='Complément (salle, parking d’entrée…).', max_length=255, verbose_name='Précision lieu')),
                ('concert_end_note', models.CharField(blank=True, help_text='Ex. 22h / 22h30 si la fin exacte n’est pas figée.', max_length=80, verbose_name='Fin de concert (approx.)')),
                ('arrival_start', models.TimeField(blank=True, null=True, verbose_name='Arrivée dès')),
                ('arrival_end', models.TimeField(blank=True, null=True, verbose_name='Arrivée jusqu’à')),
                ('soundcheck_at', models.TimeField(blank=True, null=True, verbose_name='Début des balances')),
                ('ready_at', models.TimeField(blank=True, help_text='Heure à laquelle tout le monde doit être prêt.', null=True, verbose_name='Prêt à jouer à')),
                ('parking_info', models.TextField(blank=True, verbose_name='Stationnement')),
                ('material_notes', models.TextField(blank=True, help_text='Checklist personnelle (instrument, partitions, pupitre…).', verbose_name='Matériel à prévoir')),
                ('dress_code', models.CharField(blank=True, max_length=120, verbose_name='Dress code')),
                ('closing_note', models.TextField(blank=True, verbose_name='Mot de clôture')),
                ('notified_at', models.DateTimeField(blank=True, null=True, verbose_name='Dernière notification')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Mis à jour le')),
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='roadmap', to='events.event', verbose_name='Événement')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_event_roadmaps', to=settings.AUTH_USER_MODEL, verbose_name='Mis à jour par')),
            ],
            options={
                'verbose_name': 'feuille de route concert',
                'verbose_name_plural': 'feuilles de route concert',
                'ordering': ['-event__date_debut'],
            },
        ),
    ]
