# Generated by Django 6.0.5 on 2026-07-27 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0014_event_roadmap'),
    ]

    operations = [
        migrations.AddField(
            model_name='dateproposal',
            name='deadline_reminder_sent_at',
            field=models.DateTimeField(blank=True, help_text='Horodatage du rappel J−7 avant la date limite de réponse.', null=True, verbose_name='Rappel deadline envoyé le'),
        ),
    ]
