# Generated by Django 6.0.5 on 2026-09-13 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0017_chatmessage_thread_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventroadmap',
            name='misc_info',
            field=models.TextField(blank=True, help_text='Consignes optionnelles sous les horaires (accès, repas, contacts…).', verbose_name='Infos diverses'),
        ),
    ]
